In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings("ignore")

In [2]:
# TYPES OF RECOMMNEDOR SYSTEM 

# CONTENT BASED 

# >>>>> CONTENT KE BASIS PE , CONTENT SHOW HOGA 


# COLLABRATIVE FILTERING 

# >>>> MULTIPLE PEOPLE KE RATING SE , RECOMMEND KI JAYEGI 
        
# HYNRID

#  MIX OF BOTH 1 AND 2

WE ARE GOING TO BUILD AN CONTENT BASED .

DATA PREPROCESSING > MODEL BUILDING ? WEBSITE ME CONVERT KARENGE ? THEN WE DEPLOY THE MODEL

In [3]:
movies = pd.read_csv("C:/Users/Hp/OneDrive/Desktop/tmdb_5000_movies.csv")


credits = pd.read_csv("C:/Users/Hp/OneDrive/Desktop/tmdb_5000_credits.csv")

In [4]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [5]:
movies.shape

(4803, 20)

In [6]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [7]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [8]:
movies.describe(include="all")

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
count,4.803000e+03,4803,1712,4803.000000,4803,4803,4803,4800,4803.000000,4803,4803,4802,4.803000e+03,4801.000000,4803,4803,3959,4803,4803.000000,4803.000000
unique,NaN,1175,1691,NaN,4222,37,4801,4800,NaN,3697,469,3280,NaN,NaN,544,3,3944,4800,NaN,NaN
top,NaN,"[{""id"": 18, ""name"": ""Drama""}]",http://www.missionimpossible.com/,NaN,[],en,Out of the Blue,"In the 22nd century, a paraplegic Marine is di...",NaN,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-01-01,NaN,NaN,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Based on a true story.,The Host,NaN,NaN
freq,NaN,370,4,NaN,412,4505,2,1,NaN,351,2977,10,NaN,NaN,3171,4795,3,2,NaN,NaN
mean,2.904504e+07,NaN,NaN,57165.484281,NaN,NaN,NaN,NaN,21.492301,NaN,NaN,NaN,8.226064e+07,106.875859,NaN,NaN,NaN,NaN,6.092172,690.217989
std,4.072239e+07,NaN,NaN,88694.614033,NaN,NaN,NaN,NaN,31.816650,NaN,NaN,NaN,1.628571e+08,22.611935,NaN,NaN,NaN,NaN,1.194612,1234.585891
min,0.000000e+00,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,7.900000e+05,NaN,NaN,9014.500000,NaN,NaN,NaN,NaN,4.668070,NaN,NaN,NaN,0.000000e+00,94.000000,NaN,NaN,NaN,NaN,5.600000,54.000000
50%,1.500000e+07,NaN,NaN,14629.000000,NaN,NaN,NaN,NaN,12.921594,NaN,NaN,NaN,1.917000e+07,103.000000,NaN,NaN,NaN,NaN,6.200000,235.000000
75%,4.000000e+07,NaN,NaN,58610.500000,NaN,NaN,NaN,NaN,28.313505,NaN,NaN,NaN,9.291719e+07,118.000000,NaN,NaN,NaN,NaN,6.800000,737.000000
max,3.800000e+08,NaN,NaN,459488.000000,NaN,NaN,NaN,NaN,875.581305,NaN,NaN,NaN,2.787965e+09,338.000000,NaN,NaN,NaN,NaN,10.000000,13752.000000

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [10]:
credits.describe()

            movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

In [11]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
credits.head()["title"].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       'The Dark Knight Rises', 'John Carter'], dtype=object)

In [13]:
# MERGINg TWO DATA , TITLE WISE

In [14]:
movies=movies.merge(credits,on="title")

In [15]:
movies.shape

(4809, 23)

In [16]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [18]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [19]:
# Now ,  I have to select which movies to include in my dataset.


# genres 
# id  
# keywords
# original tile 
# overview 
# CAST
#  CREW

In [20]:
movies=movies[["genres","movie_id","overview","title","keywords","cast","crew"]]

In [21]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4809 non-null   object
 1   movie_id  4809 non-null   int64
 2   overview  4806 non-null   object
 3   title     4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [22]:
movies.dtypes

genres      object
movie_id     int64
overview    object
title       object
keywords    object
cast        object
crew        object
dtype: object

In [23]:
# movie id , tags , title  


# tags kese ? 

# we start with merging the data  

# uske liye hume pre processing karna hoga ,

In [24]:
movies.isnull().sum()

genres      0
movie_id    0
overview    3
title       0
keywords    0
cast        0
crew        0
dtype: int64

In [25]:
movies.isna().sum()

genres      0
movie_id    0
overview    3
title       0
keywords    0
cast        0
crew        0
dtype: int64

In [26]:
# overview ko replace nahi kar sakta , so we drop them

In [27]:
movies.dropna(inplace=True)

In [28]:
movies.isnull().sum()

genres      0
movie_id    0
overview    0
title       0
keywords    0
cast        0
crew        0
dtype: int64

In [29]:
# now lets see is thers is any duplicates values are present or not 



movies.duplicated().sum()

0

In [30]:
# format proper karne ki try karenge 
    

#     like jese ki genre column he 
#     " " usme esa kuch he , to hum use delete kar denge with 
#     space .

In [31]:
movies["genres"].head(1)

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [32]:
movies.iloc[:1].genres

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [33]:
movies.iloc[0].genres  # genres me jo uniqyes the vo aa gaye

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [34]:
movies.iloc[0].genres  , # ye dictionary ke form me he 
                # and i want that , i make this form of list 


# ["Action","Adventure","Fantasy","Science Fiction"]

('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]',)

In [35]:
import ast 

def convert(obj) :
    L=[]

    for i in ast.literal_eval(obj) : 
        L.append(i["name"])
    return L

In [36]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [37]:
movies["genres"]=movies["genres"].apply(convert)

In [38]:
# movies.drop(columns="Genres",axis=1,inplace=True)

In [39]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,El Mariachi just wants to play his guitar and ...,El Mariachi,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[Comedy, Romance]",72766,A newlywed couple's honeymoon is upended by th...,Newlyweds,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],126186,When ambitious New York attorney Sam is sent t...,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,[Documentary],25975,Ever since the second grade when he first saw ...,My Date with Drew,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [40]:
movies["keywords"]=movies["keywords"].apply(convert)

In [41]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[Comedy, Romance]",72766,A newlywed couple's honeymoon is upended by th...,Newlyweds,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],126186,When ambitious New York attorney Sam is sent t...,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,[Documentary],25975,Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [42]:
# cast column me mujhe top 3 names  he vo chaiye , aur unke real name , not character name

In [43]:
import ast 

def convert3(obj) :
    L=[]

    counter = 0 


    for i in ast.literal_eval(obj) : 
        if counter != 3 :
            L.append(i["name"])
            counter += 1 
        else : 
            break 
    return L

In [44]:
movies["cast"] = movies["cast"].apply(convert3)

In [45]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[Comedy, Romance]",72766,A newlywed couple's honeymoon is upended by th...,Newlyweds,[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],126186,When ambitious New York attorney Sam is sent t...,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,[Documentary],25975,Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [46]:
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [47]:
import ast 

def fetch_director(obj) :
    L=[]

    for i in ast.literal_eval(obj) :
        if i["job"] == "Director" : 
            L.append(i["name"])
            break 
    return L

In [48]:
movies["crew"]=movies["crew"].apply(fetch_director)

In [49]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,"[Comedy, Romance]",72766,A newlywed couple's honeymoon is upended by th...,Newlyweds,[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,[],126186,When ambitious New York attorney Sam is sent t...,Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,[Documentary],25975,Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]

In [50]:
movies["overview"][0]  # string he  so we convet this in list 
                        #   so that i concatente this with other list

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [51]:
movies["overview"]=movies["overview"].apply(lambda x : x.split())


# Kya Ho Raha Hai? 
# apply() Function: Ye ek pandas method hai jo DataFrame ke har ek value par ek function ko lagata hai.
# lambda x: x.split(): Har string ko space (" ") ke basis par tod deta hai aur ek list me convert kar deta hai. 



# it will spllit the "" into [] list part  and space(_) ko , se replace kar rahe he

In [52]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,"[Comedy, Romance]",72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,[],126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,[Documentary],25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]

In [53]:
# aab jo bhi columns list me aab hum use concatenate kar denge aur use tag name de denge

In [54]:
# now , list columns me jo bhi space he use remove karna he 
#  RAJ GUPTA  >> RAJGUPTA
# RAJ KUMAR >>> RAJKUMAR 
#   AB RAJ ALAG  HE AND RAJGUPTA ALAG HO GAYA 


# AB AGAR ME SIRF RAJ LIKHU TO VO DONO DEGA , RAJKUMAR WALA BHI RAJGUPTA VALA BHI 


# THAT'S WHY  HUM SPACE REMOVE KARKE USE PURA MERGE KARA DETE HE 
# MEANS NO SPACE

In [55]:
movies["overview"] = movies["overview"].apply(lambda x: [item.replace(" ", "") for item in x])

In [56]:
movies["cast"] = movies["cast"].apply(lambda x: [item.replace(" ", "") for item in x])

In [57]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[culture clash, future, space war, space colon...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, based on novel, secret agent, sequel, mi...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[based on novel, mars, medallion, space travel...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[Robert Rodriguez]
4805,"[Comedy, Romance]",72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[Edward Burns]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi...","[EricMabius, KristinBooth, CrystalLowe]",[Scott Smith]
4807,[],126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,[],"[DanielHenney, ElizaCoupe, BillPaxton]",[Daniel Hsia]
4808,[Documentary],25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[obsession, camcorder, crush, dream girl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[Brian Herzlinger]

In [58]:
columns_to_clean = ['overview', 'cast', 'crew', 'keywords']  # List of columns to clean

for col in columns_to_clean:
    movies[col] = movies[col].apply(lambda x: [item.replace(" ", "") for item in x] if isinstance(x, list) else x.replace(" ", ""))

In [59]:
# movies = movies.drop(columns="Cast",axis=1,inplace=True)

In [60]:
movies

,genres,movie_id,overview,title,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,"[Comedy, Romance]",72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,[],126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,[Documentary],25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [61]:
movies["Tags"] = movies["overview"] + movies["genres"] +  movies["keywords"]  +  movies["cast"] +  movies["crew"]

In [62]:
movies

,genres,movie_id,overview,title,keywords,cast,crew,Tags
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,"[Comedy, Romance]",72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,[],126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,[Documentary],25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [63]:
# movies = movies.drop(columns="Tage",axis=1,inplace=True)

In [64]:
movies

,genres,movie_id,overview,title,keywords,cast,crew,Tags
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,"[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,"[Comedy, Romance]",72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,[],126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,[Documentary],25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [65]:
new_df = movies[["movie_id","Tags","title"]]

In [66]:
new_df

,movie_id,Tags,title
0,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar
1,285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End
2,206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre
3,49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises
4,49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter
...,...,...,...
4804,9367,"[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi
4805,72766,"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds
4806,231617,"[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered"
4807,126186,"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling
4808,25975,"[Ever, since, the, second, grade, when, he, fi...",My Date with Drew

In [67]:
new_df["Tags"] = new_df["Tags"].apply(lambda x:" ".join(x))

In [68]:
new_df

,movie_id,Tags,title
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"John Carter is a war-weary, former military ca...",John Carter
...,...,...,...
4804,9367,El Mariachi just wants to play his guitar and ...,El Mariachi
4805,72766,A newlywed couple's honeymoon is upended by th...,Newlyweds
4806,231617,"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered"
4807,126186,When ambitious New York attorney Sam is sent t...,Shanghai Calling
4808,25975,Ever since the second grade when he first saw ...,My Date with Drew

In [69]:
new_df["Tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [70]:
new_df["Tags"] = new_df["Tags"].apply(lambda x:x.lower())

In [71]:
new_df

,movie_id,Tags,title
0,19995,"in the 22nd century, a paraplegic marine is di...",Avatar
1,285,"captain barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,a cryptic message from bondâ€™s past sends him o...,Spectre
3,49026,following the death of district attorney harve...,The Dark Knight Rises
4,49529,"john carter is a war-weary, former military ca...",John Carter
...,...,...,...
4804,9367,el mariachi just wants to play his guitar and ...,El Mariachi
4805,72766,a newlywed couple's honeymoon is upended by th...,Newlyweds
4806,231617,"""signed, sealed, delivered"" introduces a dedic...","Signed, Sealed, Delivered"
4807,126186,when ambitious new york attorney sam is sent t...,Shanghai Calling
4808,25975,ever since the second grade when he first saw ...,My Date with Drew

In [72]:
# VECTORISATION  


# TEXT KO VECTOR ME CONVERT KARTE HE USE HI HUM TEXT VECTORISATION KEHTE HE 

# STOP WORDS HATA DETE HE 

from sklearn.feature_extraction.text import CountVectorizer 

cv=CountVectorizer(max_features=5000,stop_words="english")

In [73]:
vectors=cv.fit_transform(new_df["Tags"]).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [74]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [75]:
cv.get_feature_names_out()

# len(cv.get_feature_names_out())

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [76]:
# [loved,love,loving] sabke ek meaning hi he so hum ise convert karenge ek me hi

In [77]:
! pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\hp\appdata\roaming\python\python312\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\hp\appdata\roaming\python\python312\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\hp\appdata\roaming\python\python312\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\roaming\python\python312\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\hp\appdata\roaming\python\python312\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [78]:
import nltk 

from nltk.stem.porter import PorterStemmer 
ps = PorterStemmer() 

# there by 

ps.stem("loved") #-- > output love

'love'

In [79]:
ps.stem("loving")

'love'

In [80]:
def stem(text):
    y = []
    for i in text.split() : 
        y.append(ps.stem(i))

    return " ".join(y)

In [81]:
new_df["Tags"].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: Tags, Length: 4806, dtype: object

In [82]:
# now lets see  

new_df["Tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [83]:
stem("n the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron")

'n the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [84]:
# movies ke jo vectors honge space me to cosine ki help se hum angle nikaleneg ,

# so we use cosine similarity 

# higher dimensional me euclidean distance is not reliable. 


# distance directly proportional to similarity

In [85]:
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
cosine_similarity(vectors)

array([[1.        , 0.08858079, 0.05812382, ..., 0.02450715, 0.02739983,
        0.        ],
       [0.08858079, 1.        , 0.06350006, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05812382, 0.06350006, 1.        , ..., 0.02635231, 0.        ,
        0.        ],
       ...,
       [0.02450715, 0.02677398, 0.02635231, ..., 1.        , 0.0745356 ,
        0.04774099],
       [0.02739983, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05337605,
        1.        ]])

In [87]:
similarity=cosine_similarity(vectors)

similarity.shape

(4806, 4806)

In [88]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1192, 0.28039985489311264),
 (539, 0.27788500718836423),
 (507, 0.26601065911288363),
 (1214, 0.25850544834696776),
 (582, 0.25834126576556143)]

In [89]:
# 1st mpvie ka 4806 movie ke sath distance nikalna he 
# then 2nd mpvie ka 4806 movie ke sath distance nikalna he 
# then 3rd mpvie ka 4806 movie ke sath distance nikalna he  
# 4th mpvie ka 4806 movie ke sath distance nikalna he  
# ......  4906 mpvie ka 4806 movie ke sath distance nikalna he

In [90]:
sorted(similarity[0],reverse=True)

[0.9999999999999998,
 0.28039985489311264,
 0.27788500718836423,
 0.26601065911288363,
 0.25850544834696776,
 0.25834126576556143,
 0.2567480829815484,
 0.24854790640048,
 0.24659848095803594,
 0.24534987303147354,
 0.24534987303147354,
 0.2450715406979359,
 0.24324324324324326,
 0.23995690956687132,
 0.23745309047699004,
 0.2372894989381248,
 0.2369241569216954,
 0.23621543814299706,
 0.23490461932490855,
 0.23490461932490855,
 0.23394386020951635,
 0.2324952774876386,
 0.23249527748763854,
 0.22966561493131393,
 0.2279803762937766,
 0.2279803762937766,
 0.22581937608857242,
 0.22568905807670633,
 0.22555354977384034,
 0.22230800575069137,
 0.22147019900891643,
 0.22056438662814232,
 0.22056438662814232,
 0.21747941810042,
 0.21369687880543226,
 0.213352298825066,
 0.213352298825066,
 0.21137012653545936,
 0.21029989116983447,
 0.2101050788156825,
 0.20924574973887466,
 0.20878692266483084,
 0.20795009796401454,
 0.20712325533373332,
 0.20668850837512243,
 0.2056773510573183,
 0.20539846638523868,
 0.20518233866439894,
 0.20518233866439894,
 0.20391184757154646,
 0.20293851577273642,
 0.2029385157727364,
 0.2005648842255601,
 0.20032733246124987,
 0.19936305570722498,
 0.1973593560521103,
 0.19727878476642874,
 0.19510570275964212,
 0.19391446622548786,
 0.19344776406574832,
 0.19184045508446734,
 0.1917988185229168,
 0.1898315991504998,
 0.1898315991504998,
 0.1898315991504998,
 0.1891891891891892,
 0.1891891891891892,
 0.18641092980036,
 0.18641092980035998,
 0.18494886071852695,
 0.1821250481661794,
 0.18195633571851272,
 0.18195633571851272,
 0.18065550087085797,
 0.18009006755629928,
 0.18009006755629928,
 0.18009006755629928,
 0.17972365808708385,
 0.17972365808708385,
 0.17937400083354382,
 0.1771615786072478,
 0.1771615786072478,
 0.17574991006549873,
 0.17549427369736506,
 0.1752499093081954,
 0.1752499093081954,
 0.1752499093081954,
 0.1743714581157289,
 0.17155007848855516,
 0.17139779254776524,
 0.17139779254776524,
 0.17122340098907804,
 0.1696751579473019,
 0.16916516233038026,
 0.1678603981989089,
 0.1677890138035061,
 0.1677890138035061,
 0.16610264925668736,
 0.1643989873053573,
 0.1643989873053573,
 0.1643989873053573,
 0.1643989873053573,
 0.1643989873053573,
 0.1643989873053573,
 0.162746694241347,
 0.16216216216216217,
 0.16216216216216217,
 0.16120647005479025,
 0.16120647005479025,
 0.1611432394306458,
 0.15819299929208316,
 0.15819299929208316,
 0.15819299929208316,
 0.15819299929208316,
 0.15794943794779692,
 0.15794943794779692,
 0.15794943794779692,
 0.15660307954993902,
 0.15660307954993902,
 0.1559625734730109,
 0.1553424415003,
 0.1553424415003,
 0.15499685165842572,
 0.15404884978892905,
 0.1526406277181659,
 0.1522038868295523,
 0.1522038868295523,
 0.15110651212172094,
 0.15086285728094284,
 0.15086285728094284,
 0.15086285728094284,
 0.15042366316917008,
 0.15042366316917008,
 0.15007505629691606,
 0.15007505629691606,
 0.15007505629691606,
 0.15007505629691606,
 0.1487044791289829,
 0.1487044791289829,
 0.14763464883937316,
 0.14763464883937316,
 0.14763464883937316,
 0.14704292441876157,
 0.14704292441876154,
 0.14704292441876154,
 0.14704292441876154,
 0.14704292441876154,
 0.1461508458653816,
 0.1454358496691159,
 0.14543584966911588,
 0.1453095484297741,
 0.14498627873361333,
 0.1438803413133505,
 0.1438803413133505,
 0.1438803413133505,
 0.14384911389218763,
 0.14349920066683505,
 0.14349920066683505,
 0.14349920066683505,
 0.14309095175803563,
 0.14309095175803563,
 0.14309095175803563,
 0.14237369936287486,
 0.14237369936287486,
 0.14237369936287486,
 0.14165281524036175,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14091341769030624,
 0.14091341769030624,
 0.14091341769030624,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.13955413899505748,
 0.1389425035941821,
 0.1389425035941821,
 0.1389425035941821,
 0.1389425035941821,
 0.13812277665483924,
 0.1371182340382122,
 0.1371182340382122,
 0.1371182340382122,
 0.13699915608779772,
 0.13699915608779772,
 0.13699915608779772,
 0.13699915608779772,
 0.13699915608779772,
 0.13699915608779772,
 0.13699915608779772,
 0.13678822577626598,
 0.13678822577626598,
 0.13678822577626598,
 0.13513513513513514,
 0.13469012250470785,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.13334518676566626,
 0.13334518676566626,
 0.13334518676566626,
 0.13334518676566626,
 0.13334518676566626,
 0.13334518676566626,
 0.13181243254912406,
 0.13181243254912406,
 0.1316245316231641,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13065106689280268,
 0.13065106689280268,
 0.13065106689280268,
 0.13065106689280268,
 0.12996881122750908,
 0.12996881122750908,
 0.12951986753290365,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.12841755074180852,
 0.1283740414907742,
 0.1283740414907742,
 0.1283740414907742,
 0.12734290799340264,
 0.12683657235796025,
 0.12683657235796025,
 0.12683657235796025,
 0.12683657235796025,
 0.12655439943366653,
 0.12655439943366653,
 0.12655439943366653,
 0.12655439943366653,
 0.12535305264097507,
 0.12535305264097507,
 0.12535305264097507,
 0.1252721535988985,
 0.12427395320024,
 0.12427395320024,
 0.12427395320023998,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12329924047901797,
 0.12329924047901797,
 0.12329924047901797,
 0.12253577034896798,
 0.12253577034896797,
 0.12253577034896797,
 0.12253577034896797,
 0.12253577034896795,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.12141669877745292,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.11997845478343568,
 0.11961783342433499,
 0.11961783342433499,
 0.11961783342433499,
 0.11961783342433499,
 0.11961783342433499,
 0.11810771907149853,
 0.11810771907149853,
 0.11810771907149853,
 0.11789662378377888,
 0.11742784807525519,
 0.11742784807525519,
 0.11742784807525519,
 0.11742784807525519,
 0.11706342165578529,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.11624763874381928,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11510231387903269,
 0.11510231387903269,
 0.11510231387903269,
 0.11510231387903269,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.1139901881468883,
 0.11389895949029986,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11185934253567072,
 0.11185934253567072,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11083777463036817,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10892898631973956,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10793322294408637,
 0.10793322294408637,
 0.10793322294408637,
 0.10793322294408637,
 0.10793322294408637,
 0.1076244005001263,
 0.1076244005001263,
 0.1076244005001263,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10701462561817378,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.1061190899945022,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10524566699352861,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10455754681132275,
 0.10439346133241542,
 0.10439346133241542,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10274936706584831,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10195592378577323,
 0.1017387650221051,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10042266465917388,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09802861627917438,
 0.09802861627917438,
 0.09695723311274393,
 0.09695723311274393,
 0.09695723311274393,
 0.09695723311274393,
 0.09695723311274393,
 0.09687303228651607,
 0.09687303228651607,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09592022754223367,
 0.09592022754223367,
 0.09555497043061453,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.09394227846020416,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.0930725988812425,
 0.09299811099505542,
 0.09299811099505542,
 0.09248165577087424,
 0.09208185110322616,
 0.09208185110322616,
 0.09208185110322616,
 0.09208185110322616,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09032775043542898,
 0.0902256659231352,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.08967217489383125,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08915786895268649,
 0.08867021970429453,
 0.08867021970429453,
 0.08867021970429453,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.0863465783552691,
 0.0861684827823226,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08419653359482289,
 0.08419653359482289,
 0.08419653359482288,
 0.08419653359482288,
 0.08351476906593233,
 0.08351476906593233,
 0.08351476906593233,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08284930213349333,
 0.08284930213349333,
 0.08284930213349333,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08156473902861858,
 0.08156473902861858,
 0.08156473902861856,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.0787328356524048,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07702442489446452,
 0.07644397634449163,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477615,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07535215228789051,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.074458079104994,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07261932421315971,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07050168600188522,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06818952339930237,
 0.06774581282657174,
 0.06774581282657174,
 0.06774581282657174,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06650266477822091,
 0.0665026647782209,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,

In [91]:
new_df[new_df["title"]=="Batman Begins"].index[0]

119

In [92]:
def recommend(movie) :
    movie_index = new_df[new_df["title"] == movie].index[0]
    distances = similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:6]

    for i in movie_list : 
        # print(new_df.iloc[i[0]].title)
        print(i)

In [93]:
recommend("Avatar")

(1192, 0.28039985489311264)
(539, 0.27788500718836423)
(507, 0.26601065911288363)
(1214, 0.25850544834696776)
(582, 0.25834126576556143)

In [94]:
recommend("Batman Begins")

(65, 0.39803116113856707)
(3, 0.3609974361905778)
(1361, 0.34327774061437394)
(210, 0.3312739669962107)
(1360, 0.3195741847747845)

In [95]:
new_df.iloc[1216]

movie_id                                                10641
Tags        autumn in new york follows the sexual exploits...
title                                      Autumn in New York
Name: 1216, dtype: object

In [96]:
new_df.iloc[1216].title

'Autumn in New York'

In [97]:
import pickle

In [98]:
pickle.dump(new_df,open("movies.pkl","wb"))

In [99]:
new_df["title"].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [100]:
pickle.dump(new_df.to_dict(),open("movie_dict.pkl","wb"))

In [101]:
pickle.dump(similarity,open("similarity.pkl","wb"))

In [102]:
! pip install request

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [104]:
! pip install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\program files\python312\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\appdata\roaming\python\python312\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python312\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\roaming\python\python312\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\roaming\python\python312\site-packages (from requests) (2024.12.14)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
import requests

def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key=00047d05e40d2f3b2ccf4cc638fe3017&language=en-US".format(movie_id)
    response = requests.get(url)

    print(f"Status Code: {response.status_code}")  # Status code print karo
    print(f"Response Text: {response.text}")  # Response text print karo for debugging

    if response.status_code == 200:
        data = response.json()
        poster_path = data['poster_path']
        poster_url = f"https://image.tmdb.org/t/p/w500{poster_path}"
        return poster_url
    else:
        return f"Error: {response.status_code}"

# Example usage:
movie_id = 550  # Tum movie ID yahan daal sakte ho
print(fetch_poster(movie_id))

Status Code: 200
Response Text: {"adult":false,"backdrop_path":"/hZkgoQYus5vegHoetLkCJzb17zJ.jpg","belongs_to_collection":null,"budget":63000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.foxmovies.com/movies/fight-club","id":550,"imdb_id":"tt0137523","origin_country":["US"],"original_language":"en","original_title":"Fight Club","overview":"A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.","popularity":118.187,"poster_path":"/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg","production_companies":[{"id":711,"logo_path":"/tEiIH5QesdheJmDAqQwvtN60727.png","name":"Fox 2000 Pictures","origin_country":"US"},{"id":508,"logo_path":"/7cxRWzi4LsVm4Utfpr1hfARNurT.png","name":"Regency Enterprises","origin_country":"US"},{"id":4700,"logo_path":"/A32wmjrs9Psf4zw0uaixF0GXfxq.png","name":"The Linson Company","origin_country":"US"},{"id":25,"logo_path":"/qZCc1lty5FzX30aOCVRBLzaVmcp.png","name":"20th Century Fox","origin_country":"US"},{"id":20555,"logo_path":"/hD8yEGUBlHOcfHYbujp71vD8gZp.png","name":"Taurus Film","origin_country":"DE"}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1999-10-15","revenue":100853753,"runtime":139,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Mischief. Mayhem. Soap.","title":"Fight Club","video":false,"vote_average":8.438,"vote_count":29848}
https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg